build:
  version: "2.0"

account:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "Smith Ray - QA Lead"
    email: "smithr@bank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371