build:
  version: "3.0"

account:
  message: "Welcome to Bank accounts related local APIs "
  contactDetails:
    name: "Burak Karacan - Software Developer"
    email: "bkaracan94@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

