build:
  version: "1.0"

account:
  message: "Welcome to Bank accounts related prod APIs "
  contactDetails:
    name: "Ali Kaya  - Product Owner"
    email: "alikaya@bank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384