build:
  version: "3.0"

card:
  message: "Welcome to Bank cards related local APIs"
  contactDetails:
    name: "Drago Lech - Developer"
    email: "dragol@bank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
