build:
  version: "1.0"

card:
  message: "Welcome to bank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sharald@bank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721