build:
  version: "2.0"

card:
  message: "Welcome to Bank cards related QA APIs "
  contactDetails:
    name: "Mehmet Cele - QA Lead"
    email: "mcele@bank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267